language: python
python: 3.6.7
jobs:
  include:
    - name: mkdocs
      install:
        - travis_retry pip install -U mkdocs mkdocs-material
      script:
        - mkdocs build --clean --strict
      deploy:
        provider: pages
        skip-cleanup: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        local-dir: site
        on:
          branch: master
    - name: docker
      script:
        - docker build --tag "${DOCKER_IMAGE}:latest" .
      before_deploy:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - if [ -n "$TRAVIS_TAG" ]; then docker tag "${DOCKER_IMAGE}:latest" "${DOCKER_IMAGE}:${$TRAVIS_TAG}"; fi
      deploy:
        provider: script
        script: docker push "${DOCKER_IMAGE}:latest" && if [ -n "$TRAVIS_TAG" ]; then docker push "${DOCKER_IMAGE}:${TRAVIS_TAG}"; fi
      on:
        branch: master
    - name: docker
      script:
        - docker build --tag "${DOCKER_IMAGE}:latest" .
      before_deploy:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - if [ -n "$TRAVIS_TAG" ]; then docker tag "${DOCKER_IMAGE}:latest" "${DOCKER_IMAGE}:${$TRAVIS_TAG}"; fi
      deploy:
        provider: script
        script: docker push "${DOCKER_IMAGE}:latest" && if [ -n "$TRAVIS_TAG" ]; then docker push "${DOCKER_IMAGE}:${TRAVIS_TAG}"; fi
      on:
        branch: master
    - name: docker (arm32v6)
      script:
        - docker build --tag "${DOCKER_IMAGE}:arm32v6" .
      before_deploy:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      deploy:
        provider: script
        script: docker push "${DOCKER_IMAGE}:arm32v6"
      on:
        branch: master
