site_name: Cloudflare DDNS
theme:
  name: material
  palette:
    primary: amber
    accent: amber

repo_name: joshuaavalon/docker-cloudflare
repo_url: https://github.com/joshuaavalon/docker-cloudflare

extra:
  social:
    - type: github-alt
      link: https://github.com/joshuaavalon/docker-cloudflare
